apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../booksapp

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: authors
  path: patch-noerror.yaml
  # patch: |-
  #   - op: remove
  #     path: /spec/template/spec/containers/0/env/2